version: "3.7"

services:
  monsupernginx:
    image: nginx:alpine # Image utilisee
    container_name: monsupernginx # Un nom super hype
    volumes: 
     - /etc/localtime:/etc/localtime:ro # On partage l'heure du systemt
     - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro # On partage nos certificat racine 
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # alpine linux va chercher par defaut le fichier nginx a cet endroit
     - ./nginx/monsupernginx.asr.lol.crt:/cert/monsupernginx.asr.lol.crt:ro # Le certificat du serveur web
     - ./nginx/monsupernginx.asr.lol.key:/cert/monsupernginx.asr.lol.key:ro # la cle privee (droit en 400)
    ports:
     - 443:443 # on partage le reseau de la machine hote avec le container
    networks:
      - identinet
  identidock:
    container_name: appv1
    build: .
    networks:
      - identinet
  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - identinet
  redis:
    image: redis
    networks:
      - identinet
networks:
  identinet:
    driver: bridge